repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.7.2"
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: run-pytest
        name: run-pytest
        entry: pytest
        language: system
        pass_filenames: false
        types: [python]
      - id: quartodoc-build
        name: Quartodoc Build
        entry: quartodoc build
        language: system
        pass_filenames: false
      - id: quarto-render
        name: Quarto Render
        entry: quarto render
        language: system
        pass_filenames: false
